format_version: 10
pipelines:
  BuildExample:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-ba06e0b:
        git: https://github.com/albal/nodeexamples.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - Build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Build:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - servers/express/api-with-express-and-handlebars
                command: cd
                run_if: passed
            - exec:
                arguments:
                - install
                command: npm
                run_if: passed
